# Generated by Django 2.0 on 2018-01-09 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doc', '0004_auto_20180109_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='body',
            new_name='Prescription',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created',
        ),
    ]
